/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobLogsRouteImport } from './routes/job-logs'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContractReviewRouteImport } from './routes/contract-review'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobLogsRoute = JobLogsRouteImport.update({
  id: '/job-logs',
  path: '/job-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractReviewRoute = ContractReviewRouteImport.update({
  id: '/contract-review',
  path: '/contract-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PropertiesRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesRoute,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/$contractId',
  path: '/$contractId',
  getParentRoute: () => ContractsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/contract-review': typeof ContractReviewRoute
  '/documents': typeof DocumentsRoute
  '/job-logs': typeof JobLogsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/contract-review': typeof ContractReviewRoute
  '/documents': typeof DocumentsRoute
  '/job-logs': typeof JobLogsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/clients': typeof ClientsIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/contract-review': typeof ContractReviewRoute
  '/documents': typeof DocumentsRoute
  '/job-logs': typeof JobLogsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/contract-review'
    | '/documents'
    | '/job-logs'
    | '/login'
    | '/privacy'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/invoices/$invoiceId'
    | '/join/$code'
    | '/properties/$propertyId'
    | '/tasks/$taskId'
    | '/clients/'
    | '/contracts/'
    | '/invoices/'
    | '/properties/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/contract-review'
    | '/documents'
    | '/job-logs'
    | '/login'
    | '/privacy'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/invoices/$invoiceId'
    | '/join/$code'
    | '/properties/$propertyId'
    | '/tasks/$taskId'
    | '/clients'
    | '/contracts'
    | '/invoices'
    | '/properties'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/contract-review'
    | '/documents'
    | '/job-logs'
    | '/login'
    | '/privacy'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/invoices/$invoiceId'
    | '/join/$code'
    | '/properties/$propertyId'
    | '/tasks/$taskId'
    | '/clients/'
    | '/contracts/'
    | '/invoices/'
    | '/properties/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ContractReviewRoute: typeof ContractReviewRoute
  DocumentsRoute: typeof DocumentsRoute
  JobLogsRoute: typeof JobLogsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-logs': {
      id: '/job-logs'
      path: '/job-logs'
      fullPath: '/job-logs'
      preLoaderRoute: typeof JobLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-review': {
      id: '/contract-review'
      path: '/contract-review'
      fullPath: '/contract-review'
      preLoaderRoute: typeof ContractReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ContractReviewRoute: ContractReviewRoute,
  DocumentsRoute: DocumentsRoute,
  JobLogsRoute: JobLogsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  JoinCodeRoute: JoinCodeRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
