/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContractReviewRouteImport } from './routes/contract-review'
import { Route as IndexRouteImport } from './routes/index'

const ContractReviewRoute = ContractReviewRouteImport.update({
  id: '/contract-review',
  path: '/contract-review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract-review': typeof ContractReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract-review': typeof ContractReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract-review': typeof ContractReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contract-review'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contract-review'
  id: '__root__' | '/' | '/contract-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractReviewRoute: typeof ContractReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contract-review': {
      id: '/contract-review'
      path: '/contract-review'
      fullPath: '/contract-review'
      preLoaderRoute: typeof ContractReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractReviewRoute: ContractReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
